/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import Controller.*;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.*;


/**
 *
 * @author Ripple Device
 */
public class MainFrame extends javax.swing.JFrame {

    LinkedList<InventoryModel> list = new LinkedList<>();
    static int size =10;
    static String [][] addNewStack = new String [size][6];
    static String [][] updateStack = new String [size][6];
    static String [][] deleteStack = new String [size][6];

    Admin admin = new Admin("1","admin","admin.gmail.com","admin123");


    Operations operations = new Operations();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        //default init
        initComponents();


        operations.initialData();
        this.list=operations.getList();
        Structures.loadInventoryListToTable(viewTableAdmin, list);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        viewAllBtn = new javax.swing.JButton();
        addNewPanelBtn = new javax.swing.JButton();
        updatePanelBtn = new javax.swing.JButton();
        deletePanelBtn = new javax.swing.JButton();
        adminActionsPanel = new javax.swing.JPanel();
        View = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTableAdmin = new javax.swing.JTable();
        addNewPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addNewBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addNewTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addIDText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addCpNameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addPriceText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addQntText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addDateText = new javax.swing.JTextField();
        updatePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        updateTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        upIDlabel = new javax.swing.JLabel();
        upIDText = new javax.swing.JTextField();
        upNameLabel = new javax.swing.JLabel();
        upCpNameText = new javax.swing.JTextField();
        upCpNameLabel = new javax.swing.JLabel();
        upNameText = new javax.swing.JTextField();
        upPriceLabel = new javax.swing.JLabel();
        upPriceText = new javax.swing.JTextField();
        upQntLabel = new javax.swing.JLabel();
        upQntText = new javax.swing.JTextField();
        upDateLabel = new javax.swing.JLabel();
        upDateText = new javax.swing.JTextField();
        deletePanel = new javax.swing.JPanel();
        deleteText = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        deleteTable = new javax.swing.JTable();
        deleteLabel = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        deleteViewTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 900));

        adminPanel.setAlignmentX(0.0F);
        adminPanel.setAlignmentY(0.0F);
        adminPanel.setMaximumSize(new java.awt.Dimension(300, 32767));
        adminPanel.setPreferredSize(new java.awt.Dimension(300, 190));

        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        viewAllBtn.setText("View All Products");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewAllBtn);

        addNewPanelBtn.setText("Add new Product");
        addNewPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPanelBtnActionPerformed(evt);
            }
        });
        jPanel3.add(addNewPanelBtn);

        updatePanelBtn.setText("Update Product");
        updatePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePanelBtnActionPerformed(evt);
            }
        });
        jPanel3.add(updatePanelBtn);

        deletePanelBtn.setText("Delete Product");
        deletePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanelBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deletePanelBtn);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(141, 141, 141)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminActionsPanel.setLayout(new java.awt.CardLayout());

        viewTableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Company", "Price", "Quantity", "Added Date"
            }
        ));
        jScrollPane1.setViewportView(viewTableAdmin);
        if (viewTableAdmin.getColumnModel().getColumnCount() > 0) {
            viewTableAdmin.getColumnModel().getColumn(0).setResizable(false);
            viewTableAdmin.getColumnModel().getColumn(0).setPreferredWidth(10);
            viewTableAdmin.getColumnModel().getColumn(3).setResizable(false);
            viewTableAdmin.getColumnModel().getColumn(3).setPreferredWidth(15);
            viewTableAdmin.getColumnModel().getColumn(4).setResizable(false);
            viewTableAdmin.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
                .addContainerGap())
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminActionsPanel.add(View, "card2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Add New Product");

        addNewBtn.setText("Add");
        addNewBtn.setPreferredSize(new java.awt.Dimension(90, 25));
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        addNewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Company", "Price", "Quantity", "Date"
            }
        ));
        jScrollPane2.setViewportView(addNewTable);
        if (addNewTable.getColumnModel().getColumnCount() > 0) {
            addNewTable.getColumnModel().getColumn(0).setResizable(false);
            addNewTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            addNewTable.getColumnModel().getColumn(3).setResizable(false);
            addNewTable.getColumnModel().getColumn(3).setPreferredWidth(15);
            addNewTable.getColumnModel().getColumn(4).setResizable(false);
            addNewTable.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        jPanel2.setLayout(new java.awt.GridLayout(6, 3, 10, 15));

        jLabel2.setText("ID");
        jPanel2.add(jLabel2);
        jPanel2.add(addIDText);

        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jPanel2.add(addNameText);

        jLabel4.setText("Company Name");
        jPanel2.add(jLabel4);
        jPanel2.add(addCpNameText);

        jLabel6.setText("Price");
        jPanel2.add(jLabel6);
        jPanel2.add(addPriceText);

        jLabel7.setText("Quantity");
        jPanel2.add(jLabel7);
        jPanel2.add(addQntText);

        jLabel8.setText("Date");
        jPanel2.add(jLabel8);
        jPanel2.add(addDateText);

        javax.swing.GroupLayout addNewPanelLayout = new javax.swing.GroupLayout(addNewPanel);
        addNewPanel.setLayout(addNewPanelLayout);
        addNewPanelLayout.setHorizontalGroup(
            addNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewPanelLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(addNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(316, 316, 316))))
            .addGroup(addNewPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        addNewPanelLayout.setVerticalGroup(
            addNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewPanelLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(addNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminActionsPanel.add(addNewPanel, "card3");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Update Product");
        jLabel9.setRequestFocusEnabled(false);

        updateBtn.setText("Update");
        updateBtn.setPreferredSize(new java.awt.Dimension(90, 25));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        updateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Company", "Price", "Quantity", "Date"
            }
        ));
        jScrollPane3.setViewportView(updateTable);
        if (updateTable.getColumnModel().getColumnCount() > 0) {
            updateTable.getColumnModel().getColumn(0).setResizable(false);
            updateTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            updateTable.getColumnModel().getColumn(3).setResizable(false);
            updateTable.getColumnModel().getColumn(3).setPreferredWidth(15);
            updateTable.getColumnModel().getColumn(4).setResizable(false);
            updateTable.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 15));

        upIDlabel.setText("ID");
        jPanel1.add(upIDlabel);

        upIDText.setPreferredSize(new java.awt.Dimension(150, 22));
        upIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                upIDTextKeyPressed(evt);
            }
        });
        jPanel1.add(upIDText);

        upNameLabel.setText("Name");
        jPanel1.add(upNameLabel);

        upCpNameText.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(upCpNameText);

        upCpNameLabel.setText("Company");
        jPanel1.add(upCpNameLabel);

        upNameText.setColumns(2);
        jPanel1.add(upNameText);

        upPriceLabel.setText("Price");
        jPanel1.add(upPriceLabel);

        upPriceText.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(upPriceText);

        upQntLabel.setText("Quantity");
        jPanel1.add(upQntLabel);

        upQntText.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(upQntText);

        upDateLabel.setText("Date");
        jPanel1.add(upDateLabel);

        upDateText.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(upDateText);

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminActionsPanel.add(updatePanel, "card4");

        deleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Company"
            }
        ));
        jScrollPane4.setViewportView(deleteTable);
        if (deleteTable.getColumnModel().getColumnCount() > 0) {
            deleteTable.getColumnModel().getColumn(0).setResizable(false);
            deleteTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        deleteLabel.setText("Enter ID");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        deleteViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Company"
            }
        ));
        jScrollPane5.setViewportView(deleteViewTable);
        if (deleteViewTable.getColumnModel().getColumnCount() > 0) {
            deleteViewTable.getColumnModel().getColumn(0).setResizable(false);
            deleteViewTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jLabel1.setText("Delete History");

        jLabel10.setText("List of all products");

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(deleteLabel)
                        .addGap(41, 41, 41)
                        .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(deleteBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deletePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLabel)
                    .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        adminActionsPanel.add(deletePanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addNewPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPanelBtnActionPerformed
        // TODO add your handling code here:
        //Switch to Add new Panel
        CardLayout card = (CardLayout)adminActionsPanel.getLayout();
        card.show(adminActionsPanel, "card3");


    }//GEN-LAST:event_addNewPanelBtnActionPerformed

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        // TODO add your handling code here:
        //Btn to add new product to list
        
        String id = addIDText.getText().trim();
        String name = addNameText.getText().trim();
        String company = addCpNameText.getText().trim();
        String price = addPriceText.getText().trim();
        String quantity = addQntText.getText().trim();
        String date = addDateText.getText().trim();
        boolean success;

        try{
             success = operations.addProduct(addNewPanel,id, name, company, price, quantity, date);
        }
        catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid data format","Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        catch(NullPointerException e){
            logger.log(java.util.logging.Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "An error occurred while deleting the product", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (success){
            this.list = operations.getList();
            Structures.loadInventoryListToTable(viewTableAdmin, this.list);

            JOptionPane.showMessageDialog(this, "Product added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            //push to add history stack
            String [][] value =Structures.pushToStack(addNewStack,id, name, company, Double.parseDouble(price),Integer.parseInt(quantity), date);

            int rowCount = addNewTable.getRowCount();
            if(rowCount==size-1)
                JOptionPane.showMessageDialog(this, "Add new product history is full, clear list to add more", "Error", JOptionPane.ERROR_MESSAGE);
            else
                addNewStack= value;
            Structures.loadFromStack(addNewTable,addNewStack);


            //Clear the text fields after adding
            addIDText.setText("");
            addNameText.setText("");
            addCpNameText.setText("");
            addPriceText.setText("");
            addQntText.setText("");
            addDateText.setText("");
        }
       
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void updatePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePanelBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)adminActionsPanel.getLayout();
        card.show(adminActionsPanel, "card4");
        Structures.loadFromStack(updateTable, updateStack);
    }//GEN-LAST:event_updatePanelBtnActionPerformed

    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)adminActionsPanel.getLayout();
        card.show(adminActionsPanel, "card2");
        Structures.loadInventoryListToTable(viewTableAdmin, this.list);
    }//GEN-LAST:event_viewAllBtnActionPerformed

    private void deletePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanelBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)adminActionsPanel.getLayout();
        card.show(adminActionsPanel, "card5");
        Structures.loadFromStack(deleteTable, deleteStack);
        Structures.loadInventoryListToTable(deleteViewTable, list);
        
    }//GEN-LAST:event_deletePanelBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String productId=deleteText.getText();
        InventoryModel l =null;
        try {
            if (productId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Product ID To Update", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            LinkedList<InventoryModel> checkList = operations.getList();

            for (InventoryModel li : checkList) {
                if (li.getProductID().equals(productId)) {
                    l = li;
                }
            }
            if (l == null) {
                JOptionPane.showMessageDialog(this, "Product ID not found", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }


            InventoryModel model = new InventoryModel(l.getProductID(), l.getProductName(), l.getProductCompany(), l.getProductPrice(), l.getProductQuantity(), l.getAddedDate());
            operations.deleteProduct(l,deletePanel);

            //push to add history stack
            String [][] value = Structures.pushToStack(deleteStack,model.getProductID(), model.getProductName(), model.getProductCompany(), model.getProductPrice(), model.getProductQuantity(), model.getAddedDate());

            int rowCount = deleteTable.getRowCount();
            if(rowCount==size-1)
                JOptionPane.showMessageDialog(this, "Delete history is full, remove product from history to continue", "Error", JOptionPane.ERROR_MESSAGE);
            else
                deleteStack= value;
            this.list=operations.getList();
            Structures.loadFromStack(deleteTable,deleteStack);
            Structures.loadInventoryListToTable(deleteViewTable, this.list);
            //Logic to delete product from the list
            
        }catch (NullPointerException e){
            logger.log(java.util.logging.Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Prodcut ID not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        deleteText.setText("");


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String id = upIDText.getText().trim();
        String name = upNameText.getText().trim();
        String company = upCpNameText.getText().trim();
        String price = upPriceText.getText().trim();
        String quantity = upQntText.getText().trim();
        String date = upDateText.getText().trim();
        boolean success;

        try{
            success=operations.updateProduct(updatePanel,id, name, company, price, quantity, date);
            
            if (success){
                this.list=operations.getList();
                Structures.loadInventoryListToTable(viewTableAdmin, this.list);
                JOptionPane.showMessageDialog(this, "Product upated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                //push to add history stack
                String [][] value =Structures.pushToStack(updateStack,id, name, company, Double.parseDouble(price), Integer.parseInt(quantity), date);

                int rowCount = updateTable.getRowCount();
                if(rowCount==size-1)
                    JOptionPane.showMessageDialog(this, "Update history is full, clear list to add more", "Error", JOptionPane.ERROR_MESSAGE);
                else
                    updateStack= value;
                Structures.loadFromStack(updateTable,updateStack);

                //Clear the text fields after updating
                upIDText.setText("");
                upNameText.setText("");
                upCpNameText.setText("");
                upPriceText.setText("");
                upQntText.setText("");
                upDateText.setText("");
            }
            
        }
        catch (NullPointerException e){
            logger.log(java.util.logging.Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Please fill all the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (NumberFormatException e){
            logger.log(java.util.logging.Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Price and Quantity", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void upIDTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upIDTextKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (upIDText.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please Enter Product ID To Update", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                LinkedList<InventoryModel> checkList = operations.getList();
                InventoryModel l = null;
                for (InventoryModel li : checkList) {
                    if (li.getProductID().equals(upIDText.getText())) {
                        l = li;
                    }
                }
                if (l == null) {
                    JOptionPane.showMessageDialog(this, "Product ID not found", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                upIDText.setText(l.getProductID());
                upNameText.setText(l.getProductName());
                upCpNameText.setText(l.getProductCompany());
                upPriceText.setText(String.valueOf(l.getProductPrice()));
                upQntText.setText(String.valueOf(l.getProductQuantity()));
                upDateText.setText(l.getAddedDate());


            } catch (NullPointerException e) {
                logger.log(java.util.logging.Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(this, "An error occurred while fetching product details", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_upIDTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel View;
    private javax.swing.JTextField addCpNameText;
    private javax.swing.JTextField addDateText;
    private javax.swing.JTextField addIDText;
    private javax.swing.JTextField addNameText;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JPanel addNewPanel;
    private javax.swing.JButton addNewPanelBtn;
    private javax.swing.JTable addNewTable;
    private javax.swing.JTextField addPriceText;
    private javax.swing.JTextField addQntText;
    private javax.swing.JPanel adminActionsPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deletePanelBtn;
    private javax.swing.JTable deleteTable;
    private javax.swing.JTextField deleteText;
    private javax.swing.JTable deleteViewTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel upCpNameLabel;
    private javax.swing.JTextField upCpNameText;
    private javax.swing.JLabel upDateLabel;
    private javax.swing.JTextField upDateText;
    private javax.swing.JTextField upIDText;
    private javax.swing.JLabel upIDlabel;
    private javax.swing.JLabel upNameLabel;
    private javax.swing.JTextField upNameText;
    private javax.swing.JLabel upPriceLabel;
    private javax.swing.JTextField upPriceText;
    private javax.swing.JLabel upQntLabel;
    private javax.swing.JTextField upQntText;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JButton updatePanelBtn;
    private javax.swing.JTable updateTable;
    private javax.swing.JButton viewAllBtn;
    private javax.swing.JTable viewTableAdmin;
    // End of variables declaration//GEN-END:variables
}

